Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace firecracker_web.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FirecrackerController.cs
using firecracker;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace firecracker_web.Controllers
{
    public class FirecrackerController : Controller
    {
        // GET: Firecracker/Details/5
        public ActionResult Execute(string houseInput, string moduleInput, string moduleAction)
        {
            FirecrackerSerialPort.House houseId;
            Enum.TryParse<FirecrackerSerialPort.House>(houseInput, true, out houseId);

            int moduleNumber;
            int.TryParse(moduleInput, out moduleNumber);

            FirecrackerSerialPort.ModuleState moduleState;
            Enum.TryParse<FirecrackerSerialPort.ModuleState>(moduleAction, true, out moduleState);

            FirecrackerSerialPort fc = new FirecrackerSerialPort("COM3");
            fc.Initialize();
            fc.SendCommand(houseId, moduleNumber, moduleState);
            System.Threading.Thread.Sleep(1000);
            //Console.ReadKey();
            fc.Close();

            return PartialView();
        }
    }
}

Views/Default/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Switchboard</h2>


<style>
    .console-row {
        border: 1px #000 solid;
        width: 100%;
        max-width: 400px;
        padding: 5px;
    }

    .button {
        border: 1px #000 solid;
        background-color: #ccc;
        width: 50px;
        float: right;
        margin: 5px;
        text-align: center;
        cursor: pointer;
    }

    .console-text {
        vertical-align: middle;
        font-weight: bold;
        padding: 5px;
    }

    .console {
        border: 1px #000 solid;
        width: 100%;
        max-width: 400px;
    }

        .console div {
            display: inline-block;
        }

    #status{
        border: 1px #000 solid;
        width: 100%;
        max-width: 400px;
    }

    .count0{
        background-color: white;
    }
</style>

<div class="console">
    <div class="console-row">
        <div class="console-text">TV Light</div>
        <div id="A1_Off" class="button">Off</div>
        <div id="A1_On" class="button">On</div>
    </div>
    <div class="console-row">
        <div class="console-text">Lamp</div>
        <div id="A2_Off" class="button">Off</div>
        <div id="A2_On" class="button">On</div>
    </div>
    <div class="console-row">
        <div class="console-text">Bedroom Lamp</div>
        <div id="A3_Off" class="button">Off</div>
        <div id="A3_On" class="button">On</div>
    </div>
    <div class="console-row">
        <div class="console-text">All</div>
        <div id="All_Off" class="button">Off</div>
        <div id="All_On" class="button">On</div>
    </div>
    <div class="console-row">
        <div class="console-text">Lamps</div>
        <div id="Lamps_Off" class="button">Off</div>
        <div id="Lamps_On" class="button">On</div>
    </div>
    <div class="console-row">
        <div class="console-text">Dimmer</div>
        <div id="A_Dim" class="button">Dim</div>
        <div id="A_Bright" class="button">Bright</div>
    </div>
    <div class="console-row">
        <div class="console-text">Reset</div>
        <div id="Reset" class="button">Reset</div>
    </div>
</div>
<br />
<div id="status">
    <i>Executed commands will appear here</i>
</div>

<script language="javascript">
    var commandCount = 0;

    function executeAction(jsonToSend) {
        commandCount++;
        $("#status").html("<pre class=\"count" + commandCount % 2 + "\">"
                                        + jsonToSend.houseInput
                                        + jsonToSend.moduleInput + ":"
                                        + jsonToSend.moduleAction 
                                        + "</pre>" + $("#status").html());
        $.ajax({
            url: '@Url.Action("Execute", "Firecracker")',
            type: 'GET',
            dataType: 'json',
            // we set cache: false because GET requests are often cached by browsers
            // IE is particularly aggressive in that respect
            cache: false,
            data: jsonToSend,
            success:
                function () {
                    alert('we did it!');
                }

            /*function (person) {
            $('#FirstName').val(person.FirstName);
            $('#LastName').val(person.LastName);
        }*/
        });
    }

    $(function () {
        $("#A1_On").click(function () { executeAction({ houseInput: "A", moduleInput: "1", moduleAction: "on" }) });
        $("#A1_Off").click(function () { executeAction({ houseInput: "A", moduleInput: "1", moduleAction: "off" }) });
        $("#A2_On").click(function () { executeAction({ houseInput: "A", moduleInput: "2", moduleAction: "on" }) });
        $("#A2_Off").click(function () { executeAction({ houseInput: "A", moduleInput: "2", moduleAction: "off" }) });
        $("#A3_On").click(function () { executeAction({ houseInput: "A", moduleInput: "3", moduleAction: "on" }) });
        $("#A3_Off").click(function () { executeAction({ houseInput: "A", moduleInput: "3", moduleAction: "off" }) });
        $("#All_On").click(function () { executeAction({ houseInput: "A", moduleInput: "1", moduleAction: "allon" }) });
        $("#All_Off").click(function () { executeAction({ houseInput: "A", moduleInput: "1", moduleAction: "alloff" }) });
        $("#Lamps_On").click(function () { executeAction({ houseInput: "A", moduleInput: "1", moduleAction: "lampson" }) });
        $("#Lamps_Off").click(function () { executeAction({ houseInput: "A", moduleInput: "1", moduleAction: "lampsoff" }) });
        $("#A_Dim").click(function () { executeAction({ houseInput: "A", moduleInput: "1", moduleAction: "dim" }) });
        $("#A_Bright").click(function () { executeAction({ houseInput: "A", moduleInput: "1", moduleAction: "bright" }) });
        $("#Reset").click(function () { executeAction({ houseInput: "A", moduleInput: "1", moduleAction: "reset" }) });
    });
</script>